### ISSUE TITLE
feature: supports custom directories

### ISSUE THREAD

**Issue by guobin211** [BlackHole1/idea-spell-check#15]
1. {project}/.vscode/cspell.json
2. {project}/.idea/cspell.json

**Comment by BlackHole1** [comment]
@guobin211  Can you give examples of the format of such files? Is it the same as other cspell.json formats?

**Comment by BlackHole1** [comment]
No need, I've already found it

**Comment by guobin211** [comment]
@BlackHole1 I mentioned a pr, please check it
https://github.com/BlackHole1/idea-spell-check/pull/16
